### ISSUE TITLE
Convert the datagrid page to be a CRUD interface

### ISSUE THREAD

**Issue by warpech** [Starcounter/UniformDocs#229]
Right now the datagrid page is too simple for practical use. Convert it to do CRUD operations on a database object, based on `<hot-table>`.

**Comment by warpech** [comment]
@miyconst presented the requirements in https://github.com/Starcounter/RebelsLounge/issues/224#issuecomment-349266838

**Comment by miyconst** [comment]
Big vote up for the issue from me.

**Comment by warpech** [comment]
It should use `uni-data-table` (https://github.com/Starcounter/uniform.css/issues/112). @PatrykSzwer can you pls work on the view-model part of it?

**Comment by PatrykSzwer** [comment]
I assume It can be closed since `uni-data-table` is implemented already in UniformDocs. Reopen if you thing differently.
