### ISSUE TITLE
Layout is broken in Egde

### ISSUE THREAD

**Issue by tomalec** [Starcounter/UniformDocs#307]
### Steps to reproduce
1. Open http://localhost:8080/KitchenSink/Native in Edge

### Expected result
To see more-or-less same thing as in Chrome or FF

### Actual result
The menu and cards are not visible

##### Involved apps' version

- @5c34b5fda06c927c02ab9a0e00afced6d4cf73dc
 
##### Browsers affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [?] Safari

### Screenshot
![image](https://user-images.githubusercontent.com/17435/40013055-ce130cf6-57ac-11e8-83d6-85588348a26b.png)

**Comment by warpech** [comment]
Closing because we do not support EdgeHTML at this time and Edge soon moves to Chromium
