### ISSUE TITLE
Deploy UniformDocs at the new web domain

### ISSUE THREAD

**Issue by warpech** [Starcounter/UniformDocs#320]
Deploy UniformDocs at the new web domain

**Comment by warpech** [comment]
The task about buying the new web domains is here: https://github.com/Starcounter/CompanyTrack/issues/404

For the time being, I created an alias `uniform.starcounter.io` that points to the same server as `kitchensink.starcounter.io`

**Comment by warpech** [comment]
This is almost done. 

@alshakero could you pls fix the links in `starcounter.io` to point to the new domain?

**Comment by alshakero** [comment]
Sure!

**Comment by alshakero** [comment]
Closing as all done https://github.com/Starcounter/Docs/pull/237.

**Comment by warpech** [comment]
> @alshakero could you pls fix the links in starcounter.io to point to the new domain?

This was not done. I will do it.

**Comment by warpech** [comment]
Done
