### ISSUE TITLE
Tests are failing with "The name 'Blender' does not exist in the current context"

### ISSUE THREAD

**Issue by alshakero** [Starcounter/UniformDocs#332]
The build details are here: https://teamcity.starcounter.org/viewLog.html?buildId=60392&buildTypeId=Apps_UniformDocs_UniformDocsMaster24branchWithStarcounterDevelopNightly&tab=buildLog

I think it's a level1 issue since the build was passing before and no changes happened to this app.

**Comment by warpech** [comment]
Can this be closed now?

**Comment by alshakero** [comment]
Yes. Fixed in https://github.com/Starcounter/UniformDocs/pull/333
