### ISSUE TITLE
Invalid Menu Item - UniformDocs/Datagrid

### ISSUE THREAD

**Issue by miyconst** [Starcounter/UniformDocs#335]
There is an invalid Menu Item which leads to a 404 page:

- [Datagrid](https://uniform.starcounter.io/UniformDocs/Datagrid).

![image](https://user-images.githubusercontent.com/6435556/42635260-e045de28-85e5-11e8-96ad-92fec175b25e.png)

**Comment by warpech** [comment]
Thanks for reporting. Closing as done, will be released soon
