### ISSUE TITLE
Action trigger trick works only for leaf nodes

### ISSUE THREAD

**Issue by tomalec** [Starcounter/UniformDocs#344]
I'm not sure if this is the right repo to reprt such problem, as it is not related to Design System, but to deta binding system and the way we integrate our Palindrom, with Polymer, with common UI patterns.

The issue was discovered by @kegor at https://github.com/Starcounter/Showroom/pull/8#discussion_r205279916 After some investigation it seems like it may affect other cases as well. I isolated the problem to [the view](https://github.com/Starcounter/Showroom/blob/3ab77455a50609e417a900c968b7994a97eeecdb/src/Showroom/wwwroot/Showroom/views/ProductsPage.html) that looks like
```html
﻿<link rel="import" href="/sys/polymer/polymer.html">

<template>
    <dom-bind>
        <template is="dom-bind">
            <div value="{{model.Categories.0.Products.5.RecommendedProducts.0.OpenRecommendedProductModalTrigger$::click}}" onmousedown="++this.value;">
                inline replaces value
                <b>nested removes triggering an error</b>
            </div>
        </template>
    </dom-bind>
</template>

```

### Steps to reproduce
1. Bind a property value to trigger an action as we suggest in docs: `<element value="{{model.Trigger$::click}}" onmousedown="++this.value;">`
2. Add some inline text to the element,
3. Add another element to the bound one.
4. Click on inline text,
5. Click on nested element

### Expected result
Clicking on inline text and nested element should increase the value, by `replace` JSON Patch

### Actual result
Clicking inline text `replaces` as expected, clicking nested element `remove`s the value

##### Starcounter version 2.4.0.6562

- https://github.com/Starcounter/Showroom/commit/0c14755ee580d514e6d290d5497ceb9d170651f4 (master)
- Polymer 2.6.0
 
##### Browsers affected

- [x] Chrome
- [?] Firefox
- [?] Edge
- [?] Safari

**Comment by tomalec** [comment]
Seems to be related to pretty old https://github.com/Polymer/polymer/issues/2497

**Comment by alshakero** [comment]
This is a very old issue that we faced earlier and AFAIR @miyconst suffered the most from it. @miyconst do you rememeber what was the quickest workaround? I can't remember where was the issue filed, if you could link to it it would be great.

**Comment by tomalec** [comment]
My PR for Polymer 2.x was approved. Hopefully, will be merged soon, so we will not have to waste any time on workarounds.

**Comment by alshakero** [comment]
For the record. Out of curiosity I digged the issue history and the workaround was to give child elements `pointer-events: none` if someone ever needs that. Explained [`here`](https://github.com/Starcounter/UniformDocs/pull/134#issuecomment-309726468).

**Comment by warpech** [comment]
It is literally provided as part of Uniform documentation: https://uniform.starcounter.io/UniformDocs/Button:

> Because of an issue in Polymer 1, data bindings for buttons with child elements writes undefined value to the view-model property bound to the buttons, which leads to server disconnection. As a workaround, set the `pointer-events` property to `none` on the children of the button.

**Comment by tomalec** [comment]
Seems it's no longer applicable to current Showroom codebase, please feel free to reopen if you think otherwise.
