### ISSUE TITLE
Present the way to do blendable menus

### ISSUE THREAD

**Issue by warpech** [Starcounter/UniformDocs#351]
Present the way to do blendable menus, including blending rules.

Then, `<slot-all>` used in #343 can be removed from the left navigation in `MasterPage.html`, because the information about blendable menus will be a more realistic presentation of that.

**Comment by tomalec** [comment]
Sorry, but I don't understand 

> because the information about blendable menus will be a more realistic presentation of that.

What would blending rules change for slot names? I think `<slot-all>` should be used anyway. As parent view developer you never know what elements, with what slot names will get blended into partial/sub view

**Comment by warpech** [comment]
It was discussed today on a meeting with me and @tomalec, that we will keep the current blendable menu on the left to eat our dogfood. 

@tomalec will add a page about blendable menus which will include a simple blended menu of 4 items, that is used in 3 examples:

- side navigation that uses `uni-layout-left-nav`
- dropdown similar to the one used in the Timeline app
- CSS Grid similar to the one used in "Choose payment method" screen in the Orders app (user story 8.19)

Keep in mind that we can blend navigation links or buttons, but these two kinds rarely should be combined.

As the explanatory text on this page you can use Rolf's notes: https://drive.google.com/drive/u/0/folders/1BSitAJuoPTVXBUz4A2QRzAmN9QXU51tW (see two document's called "Menus")

More or less desired look and feel examples:

<img width="214" alt="screen shot 2018-08-03 at 11 32 28" src="https://user-images.githubusercontent.com/566463/43636179-a2414490-9711-11e8-9ce2-01248c2908dc.png">

<img width="577" alt="screen shot 2018-08-03 at 11 35 04" src="https://user-images.githubusercontent.com/566463/43636183-a3febe0c-9711-11e8-8e03-b86a43bb3d40.png">

<img width="167" alt="screen shot 2018-08-03 at 11 37 26" src="https://user-images.githubusercontent.com/566463/43636187-a60ac7d6-9711-11e8-81c8-a6b4b62fb25e.png">

**Comment by warpech** [comment]
Done and deployed at https://uniform.starcounter.io/UniformDocs/BlendableMenu
