### ISSUE TITLE
Pagination - Wrong design

### ISSUE THREAD

**Issue by andwah** [Starcounter/UniformDocs#368]
### Steps to reproduce
1. Navigate to https://uniform.starcounter.io/UniformDocs/Pagination
### Expected result
![image](https://user-images.githubusercontent.com/2656996/44987015-fb835700-af85-11e8-8d78-e2db52a46bd4.png)

### Actual result
![image](https://user-images.githubusercontent.com/2656996/44986986-e73f5a00-af85-11e8-97ce-558c92f8e955.png)

**Comment by alshakero** [comment]
PR in https://github.com/Starcounter/uniform.css/pull/193

**Comment by warpech** [comment]
Closing as done in PR #193
